server:
  port: 8080
  servlet:
    context-path: /
spring:
  datasource:
    url: jdbc:h2:mem:test
    username: sa
    password:
    driver-class-name: org.h2.Driver

  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        default_batch_fetch_size: 500 # ??? ??? ???? ?? ???
    open-in-view: false # ??? ????? ????? ???? ??? ??


  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 100MB

  jwt:
    secret: JYGu7LnAjPxE1Hw9404R+guJVN91HYj3DxHT927j3EHmbAnTqi1AIGDSbyZMNudGN2+Ux8ZriRtN+D2V90jsHA==
    access-expiration: 3600000
    refresh-expiration: 1209600000


logging:
  level:
    org.hibernate.type: trace

